### ISSUE TITLE
more updated tutorial

### ISSUE THREAD

**Issue by swuecho** [bucardo/bucardo_org#5]
I try to follow the pgbench tutorial. found it is outdated. this one is better and more up to dated. https://www.compose.com/articles/using-bucardo-5-3-to-migrate-a-live-postgresql-database/

**Comment by jonjensen** [comment]
Thanks for the report. We updated the pgbench tutorial recently [in this commit](https://github.com/bucardo/bucardo_org/commit/4e502e979c51f6bfa) and verified everything works currently.
