### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by fpuga** [bucardo/bucardo_org#7]
I've been using Bucardo v4.5 for some time and it is a great product but in the process to migrate to Bucardo v5.x i found that the documentation is a bit broken.

Are you open to a PR:

* Fix markdown code style to use 4 spaces and remote the backticks in the variable names
* Delete some duplicated pages like Documentation/Overview.md, Changes.md that is already in the main repo, merge `removetable.md` with `remove_table.md`, ...
* Fix hiperlinks using [link](https://jekyllrb.com/docs/liquid/tags/#link) to break the build is a link is pointing to no-where
* Maybe move all comand reference markdown files to their own folder
* ...

**Comment by machack666** [comment]
Hi @fpuga -- the documentation is a known weakness here; it was a rushed conversion of previous wiki content, so we'd gladly accept any improvements to this; just haven't had the tuits.

Thanks!
